
version: '3.7'
services: 
   
    eureka-server:
        image: cmkalimuthu/eureka-server
        ports: 
            - "8761:8761"
        restart: always
       
        networks:
            - app-network
    
    truyum-zuul-gateway:
        image: cmkalimuthu/truyum-zuul-gateway
        ports: 
            - "8083-8182:8083"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
                
        depends_on:
            - eureka-server
        networks:
            - app-network
 
    spring-rest-api:
        image: cmkalimuthu/spring-rest-api
        ports: 
            - "8080-8179:8080"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
        
        depends_on:
            - eureka-server
        networks:
            - app-network

 
# Networks to be created to facilitate communication between containers
networks:
    app-network:  
    
